/* Generated by the Nim Compiler v0.19.9 */
/*   (c) 2019 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var NTI43032 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI198074 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI46862 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI200577 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI84448 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84444 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84440 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84436 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84432 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84428 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84424 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84420 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84416 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84412 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84408 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84404 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84400 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84396 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84392 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84388 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84384 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84380 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84376 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84372 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI84205 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI84283 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI84281 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI84227 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI84565 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI84563 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI84561 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI84231 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI84229 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI86305 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI46850 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI46858 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI43006 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI63156 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI46808 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI46914 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI43016 = {size: 0,kind: 40,base: null,node: null,finalizer: null};
var NTI43040 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI43042 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI46908 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI46826 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI46828 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI46842 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI46846 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI46846 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI46846.node = NNI46846;
var NNI46842 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI46842.node = NNI46842;
var NNI46828 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI46828.node = NNI46828;
NTI46908.base = NTI46826;
NTI46914.base = NTI46826;
var NNI46826 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI46908, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI43042, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI43040, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI43040, name: "trace", sons: null}, 
{kind: 1, offset: "raiseId", len: 0, typ: NTI43016, name: "raiseId", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI46914, name: "up", sons: null}]};
NTI46826.node = NNI46826;
var NNI46808 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI46808.node = NNI46808;
NTI46826.base = NTI46808;
NTI46828.base = NTI46826;
NTI46842.base = NTI46828;
NTI46846.base = NTI46842;
var NNI63156 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI43042, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI43006, name: "Field1", sons: null}]};
NTI63156.node = NNI63156;
var NNI46858 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI46858.node = NNI46858;
NTI46858.base = NTI46828;
var NNI46850 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI46850.node = NNI46850;
NTI46850.base = NTI46828;
NTI84561.base = NTI84229;
NTI84563.base = NTI84229;
NTI84565.base = NTI84229;
var NNI84227 = {kind: 2, offset: 0, typ: null, name: null, len: 12, sons: {"1": {kind: 1, offset: 1, typ: NTI84227, name: "ElementNode", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI84227, name: "AttributeNode", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI84227, name: "TextNode", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI84227, name: "CDATANode", len: 0, sons: null}, 
"5": {kind: 1, offset: 5, typ: NTI84227, name: "EntityRefNode", len: 0, sons: null}, 
"6": {kind: 1, offset: 6, typ: NTI84227, name: "EntityNode", len: 0, sons: null}, 
"7": {kind: 1, offset: 7, typ: NTI84227, name: "ProcessingInstructionNode", len: 0, sons: null}, 
"8": {kind: 1, offset: 8, typ: NTI84227, name: "CommentNode", len: 0, sons: null}, 
"9": {kind: 1, offset: 9, typ: NTI84227, name: "DocumentNode", len: 0, sons: null}, 
"10": {kind: 1, offset: 10, typ: NTI84227, name: "DocumentTypeNode", len: 0, sons: null}, 
"11": {kind: 1, offset: 11, typ: NTI84227, name: "DocumentFragmentNode", len: 0, sons: null}, 
"12": {kind: 1, offset: 12, typ: NTI84227, name: "NotationNode", len: 0, sons: null}}};
NTI84227.node = NNI84227;
var NNI84283 = {kind: 2, len: 91, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "background", len: 0, typ: NTI43042, name: "background", sons: null}, 
{kind: 1, offset: "backgroundAttachment", len: 0, typ: NTI43042, name: "backgroundAttachment", sons: null}, 
{kind: 1, offset: "backgroundColor", len: 0, typ: NTI43042, name: "backgroundColor", sons: null}, 
{kind: 1, offset: "backgroundImage", len: 0, typ: NTI43042, name: "backgroundImage", sons: null}, 
{kind: 1, offset: "backgroundPosition", len: 0, typ: NTI43042, name: "backgroundPosition", sons: null}, 
{kind: 1, offset: "backgroundRepeat", len: 0, typ: NTI43042, name: "backgroundRepeat", sons: null}, 
{kind: 1, offset: "border", len: 0, typ: NTI43042, name: "border", sons: null}, 
{kind: 1, offset: "borderBottom", len: 0, typ: NTI43042, name: "borderBottom", sons: null}, 
{kind: 1, offset: "borderBottomColor", len: 0, typ: NTI43042, name: "borderBottomColor", sons: null}, 
{kind: 1, offset: "borderBottomStyle", len: 0, typ: NTI43042, name: "borderBottomStyle", sons: null}, 
{kind: 1, offset: "borderBottomWidth", len: 0, typ: NTI43042, name: "borderBottomWidth", sons: null}, 
{kind: 1, offset: "borderColor", len: 0, typ: NTI43042, name: "borderColor", sons: null}, 
{kind: 1, offset: "borderLeft", len: 0, typ: NTI43042, name: "borderLeft", sons: null}, 
{kind: 1, offset: "borderLeftColor", len: 0, typ: NTI43042, name: "borderLeftColor", sons: null}, 
{kind: 1, offset: "borderLeftStyle", len: 0, typ: NTI43042, name: "borderLeftStyle", sons: null}, 
{kind: 1, offset: "borderLeftWidth", len: 0, typ: NTI43042, name: "borderLeftWidth", sons: null}, 
{kind: 1, offset: "borderRight", len: 0, typ: NTI43042, name: "borderRight", sons: null}, 
{kind: 1, offset: "borderRightColor", len: 0, typ: NTI43042, name: "borderRightColor", sons: null}, 
{kind: 1, offset: "borderRightStyle", len: 0, typ: NTI43042, name: "borderRightStyle", sons: null}, 
{kind: 1, offset: "borderRightWidth", len: 0, typ: NTI43042, name: "borderRightWidth", sons: null}, 
{kind: 1, offset: "borderStyle", len: 0, typ: NTI43042, name: "borderStyle", sons: null}, 
{kind: 1, offset: "borderTop", len: 0, typ: NTI43042, name: "borderTop", sons: null}, 
{kind: 1, offset: "borderTopColor", len: 0, typ: NTI43042, name: "borderTopColor", sons: null}, 
{kind: 1, offset: "borderTopStyle", len: 0, typ: NTI43042, name: "borderTopStyle", sons: null}, 
{kind: 1, offset: "borderTopWidth", len: 0, typ: NTI43042, name: "borderTopWidth", sons: null}, 
{kind: 1, offset: "borderWidth", len: 0, typ: NTI43042, name: "borderWidth", sons: null}, 
{kind: 1, offset: "bottom", len: 0, typ: NTI43042, name: "bottom", sons: null}, 
{kind: 1, offset: "captionSide", len: 0, typ: NTI43042, name: "captionSide", sons: null}, 
{kind: 1, offset: "clear", len: 0, typ: NTI43042, name: "clear", sons: null}, 
{kind: 1, offset: "clip", len: 0, typ: NTI43042, name: "clip", sons: null}, 
{kind: 1, offset: "color", len: 0, typ: NTI43042, name: "color", sons: null}, 
{kind: 1, offset: "cursor", len: 0, typ: NTI43042, name: "cursor", sons: null}, 
{kind: 1, offset: "direction", len: 0, typ: NTI43042, name: "direction", sons: null}, 
{kind: 1, offset: "display", len: 0, typ: NTI43042, name: "display", sons: null}, 
{kind: 1, offset: "emptyCells", len: 0, typ: NTI43042, name: "emptyCells", sons: null}, 
{kind: 1, offset: "cssFloat", len: 0, typ: NTI43042, name: "cssFloat", sons: null}, 
{kind: 1, offset: "font", len: 0, typ: NTI43042, name: "font", sons: null}, 
{kind: 1, offset: "fontFamily", len: 0, typ: NTI43042, name: "fontFamily", sons: null}, 
{kind: 1, offset: "fontSize", len: 0, typ: NTI43042, name: "fontSize", sons: null}, 
{kind: 1, offset: "fontStretch", len: 0, typ: NTI43042, name: "fontStretch", sons: null}, 
{kind: 1, offset: "fontStyle", len: 0, typ: NTI43042, name: "fontStyle", sons: null}, 
{kind: 1, offset: "fontVariant", len: 0, typ: NTI43042, name: "fontVariant", sons: null}, 
{kind: 1, offset: "fontWeight", len: 0, typ: NTI43042, name: "fontWeight", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI43042, name: "height", sons: null}, 
{kind: 1, offset: "left", len: 0, typ: NTI43042, name: "left", sons: null}, 
{kind: 1, offset: "letterSpacing", len: 0, typ: NTI43042, name: "letterSpacing", sons: null}, 
{kind: 1, offset: "lineHeight", len: 0, typ: NTI43042, name: "lineHeight", sons: null}, 
{kind: 1, offset: "listStyle", len: 0, typ: NTI43042, name: "listStyle", sons: null}, 
{kind: 1, offset: "listStyleImage", len: 0, typ: NTI43042, name: "listStyleImage", sons: null}, 
{kind: 1, offset: "listStylePosition", len: 0, typ: NTI43042, name: "listStylePosition", sons: null}, 
{kind: 1, offset: "listStyleType", len: 0, typ: NTI43042, name: "listStyleType", sons: null}, 
{kind: 1, offset: "margin", len: 0, typ: NTI43042, name: "margin", sons: null}, 
{kind: 1, offset: "marginBottom", len: 0, typ: NTI43042, name: "marginBottom", sons: null}, 
{kind: 1, offset: "marginLeft", len: 0, typ: NTI43042, name: "marginLeft", sons: null}, 
{kind: 1, offset: "marginRight", len: 0, typ: NTI43042, name: "marginRight", sons: null}, 
{kind: 1, offset: "marginTop", len: 0, typ: NTI43042, name: "marginTop", sons: null}, 
{kind: 1, offset: "maxHeight", len: 0, typ: NTI43042, name: "maxHeight", sons: null}, 
{kind: 1, offset: "maxWidth", len: 0, typ: NTI43042, name: "maxWidth", sons: null}, 
{kind: 1, offset: "minHeight", len: 0, typ: NTI43042, name: "minHeight", sons: null}, 
{kind: 1, offset: "minWidth", len: 0, typ: NTI43042, name: "minWidth", sons: null}, 
{kind: 1, offset: "overflow", len: 0, typ: NTI43042, name: "overflow", sons: null}, 
{kind: 1, offset: "padding", len: 0, typ: NTI43042, name: "padding", sons: null}, 
{kind: 1, offset: "paddingBottom", len: 0, typ: NTI43042, name: "paddingBottom", sons: null}, 
{kind: 1, offset: "paddingLeft", len: 0, typ: NTI43042, name: "paddingLeft", sons: null}, 
{kind: 1, offset: "paddingRight", len: 0, typ: NTI43042, name: "paddingRight", sons: null}, 
{kind: 1, offset: "paddingTop", len: 0, typ: NTI43042, name: "paddingTop", sons: null}, 
{kind: 1, offset: "pageBreakAfter", len: 0, typ: NTI43042, name: "pageBreakAfter", sons: null}, 
{kind: 1, offset: "pageBreakBefore", len: 0, typ: NTI43042, name: "pageBreakBefore", sons: null}, 
{kind: 1, offset: "pointerEvents", len: 0, typ: NTI43042, name: "pointerEvents", sons: null}, 
{kind: 1, offset: "position", len: 0, typ: NTI43042, name: "position", sons: null}, 
{kind: 1, offset: "right", len: 0, typ: NTI43042, name: "right", sons: null}, 
{kind: 1, offset: "scrollbar3dLightColor", len: 0, typ: NTI43042, name: "scrollbar3dLightColor", sons: null}, 
{kind: 1, offset: "scrollbarArrowColor", len: 0, typ: NTI43042, name: "scrollbarArrowColor", sons: null}, 
{kind: 1, offset: "scrollbarBaseColor", len: 0, typ: NTI43042, name: "scrollbarBaseColor", sons: null}, 
{kind: 1, offset: "scrollbarDarkshadowColor", len: 0, typ: NTI43042, name: "scrollbarDarkshadowColor", sons: null}, 
{kind: 1, offset: "scrollbarFaceColor", len: 0, typ: NTI43042, name: "scrollbarFaceColor", sons: null}, 
{kind: 1, offset: "scrollbarHighlightColor", len: 0, typ: NTI43042, name: "scrollbarHighlightColor", sons: null}, 
{kind: 1, offset: "scrollbarShadowColor", len: 0, typ: NTI43042, name: "scrollbarShadowColor", sons: null}, 
{kind: 1, offset: "scrollbarTrackColor", len: 0, typ: NTI43042, name: "scrollbarTrackColor", sons: null}, 
{kind: 1, offset: "tableLayout", len: 0, typ: NTI43042, name: "tableLayout", sons: null}, 
{kind: 1, offset: "textAlign", len: 0, typ: NTI43042, name: "textAlign", sons: null}, 
{kind: 1, offset: "textDecoration", len: 0, typ: NTI43042, name: "textDecoration", sons: null}, 
{kind: 1, offset: "textIndent", len: 0, typ: NTI43042, name: "textIndent", sons: null}, 
{kind: 1, offset: "textTransform", len: 0, typ: NTI43042, name: "textTransform", sons: null}, 
{kind: 1, offset: "transform", len: 0, typ: NTI43042, name: "transform", sons: null}, 
{kind: 1, offset: "top", len: 0, typ: NTI43042, name: "top", sons: null}, 
{kind: 1, offset: "verticalAlign", len: 0, typ: NTI43042, name: "verticalAlign", sons: null}, 
{kind: 1, offset: "visibility", len: 0, typ: NTI43042, name: "visibility", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI43042, name: "width", sons: null}, 
{kind: 1, offset: "wordSpacing", len: 0, typ: NTI43042, name: "wordSpacing", sons: null}, 
{kind: 1, offset: "zIndex", len: 0, typ: NTI43006, name: "zIndex", sons: null}]};
NTI84283.node = NNI84283;
NTI84283.base = NTI46808;
NTI84281.base = NTI84283;
var NNI84231 = {kind: 2, len: 14, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "attributes", len: 0, typ: NTI84561, name: "attributes", sons: null}, 
{kind: 1, offset: "childNodes", len: 0, typ: NTI84563, name: "childNodes", sons: null}, 
{kind: 1, offset: "children", len: 0, typ: NTI84565, name: "children", sons: null}, 
{kind: 1, offset: "data", len: 0, typ: NTI43042, name: "data", sons: null}, 
{kind: 1, offset: "firstChild", len: 0, typ: NTI84229, name: "firstChild", sons: null}, 
{kind: 1, offset: "lastChild", len: 0, typ: NTI84229, name: "lastChild", sons: null}, 
{kind: 1, offset: "nextSibling", len: 0, typ: NTI84229, name: "nextSibling", sons: null}, 
{kind: 1, offset: "nodeName", len: 0, typ: NTI43042, name: "nodeName", sons: null}, 
{kind: 1, offset: "nodeType", len: 0, typ: NTI84227, name: "nodeType", sons: null}, 
{kind: 1, offset: "nodeValue", len: 0, typ: NTI43042, name: "nodeValue", sons: null}, 
{kind: 1, offset: "parentNode", len: 0, typ: NTI84229, name: "parentNode", sons: null}, 
{kind: 1, offset: "previousSibling", len: 0, typ: NTI84229, name: "previousSibling", sons: null}, 
{kind: 1, offset: "innerHTML", len: 0, typ: NTI43042, name: "innerHTML", sons: null}, 
{kind: 1, offset: "style", len: 0, typ: NTI84281, name: "style", sons: null}]};
NTI84231.node = NNI84231;
var NNI84205 = {kind: 2, len: 20, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "onabort", len: 0, typ: NTI84372, name: "onabort", sons: null}, 
{kind: 1, offset: "onblur", len: 0, typ: NTI84376, name: "onblur", sons: null}, 
{kind: 1, offset: "onchange", len: 0, typ: NTI84380, name: "onchange", sons: null}, 
{kind: 1, offset: "onclick", len: 0, typ: NTI84384, name: "onclick", sons: null}, 
{kind: 1, offset: "ondblclick", len: 0, typ: NTI84388, name: "ondblclick", sons: null}, 
{kind: 1, offset: "onerror", len: 0, typ: NTI84392, name: "onerror", sons: null}, 
{kind: 1, offset: "onfocus", len: 0, typ: NTI84396, name: "onfocus", sons: null}, 
{kind: 1, offset: "onkeydown", len: 0, typ: NTI84400, name: "onkeydown", sons: null}, 
{kind: 1, offset: "onkeypress", len: 0, typ: NTI84404, name: "onkeypress", sons: null}, 
{kind: 1, offset: "onkeyup", len: 0, typ: NTI84408, name: "onkeyup", sons: null}, 
{kind: 1, offset: "onload", len: 0, typ: NTI84412, name: "onload", sons: null}, 
{kind: 1, offset: "onmousedown", len: 0, typ: NTI84416, name: "onmousedown", sons: null}, 
{kind: 1, offset: "onmousemove", len: 0, typ: NTI84420, name: "onmousemove", sons: null}, 
{kind: 1, offset: "onmouseout", len: 0, typ: NTI84424, name: "onmouseout", sons: null}, 
{kind: 1, offset: "onmouseover", len: 0, typ: NTI84428, name: "onmouseover", sons: null}, 
{kind: 1, offset: "onmouseup", len: 0, typ: NTI84432, name: "onmouseup", sons: null}, 
{kind: 1, offset: "onreset", len: 0, typ: NTI84436, name: "onreset", sons: null}, 
{kind: 1, offset: "onselect", len: 0, typ: NTI84440, name: "onselect", sons: null}, 
{kind: 1, offset: "onsubmit", len: 0, typ: NTI84444, name: "onsubmit", sons: null}, 
{kind: 1, offset: "onunload", len: 0, typ: NTI84448, name: "onunload", sons: null}]};
NTI84205.node = NNI84205;
NTI84205.base = NTI46808;
NTI84231.base = NTI84205;
NTI84229.base = NTI84231;
NTI86305.base = NTI84229;
NTI200577.base = NTI43042;
var NNI46862 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI46862.node = NNI46862;
NTI46862.base = NTI46828;
var NNI198074 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI43006, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI43032, name: "Field1", sons: null}]};
NTI198074.node = NNI198074;

function makeNimstrLit(c_65258) {
		  var ln = c_65258.length;
  var result = new Array(ln);
  for (var i = 0; i < ln; ++i) {
    result[i] = c_65258.charCodeAt(i);
  }
  return result;
  

	
}

function setConstr() {
		    var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

	
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_66227, src_66228, ti_66229) {
	var result_66419 = null;

		switch (ti_66229.kind) {
		case 21:
		case 22:
		case 23:
		case 5:
			if (!(is_fat_pointer_66201(ti_66229))) {
			result_66419 = src_66228;
			}
			else {
				result_66419 = [src_66228[0], src_66228[1]];
			}
			
			break;
		case 19:
			      if (dest_66227 === null || dest_66227 === undefined) {
        dest_66227 = {};
      }
      else {
        for (var key in dest_66227) { delete dest_66227[key]; }
      }
      for (var key in src_66228) { dest_66227[key] = src_66228[key]; }
      result_66419 = dest_66227;
    
			break;
		case 18:
		case 17:
			if (!((ti_66229.base == null))) {
			result_66419 = nimCopy(dest_66227, src_66228, ti_66229.base);
			}
			else {
			if ((ti_66229.kind == 17)) {
			result_66419 = (dest_66227 === null || dest_66227 === undefined) ? {m_type: ti_66229} : dest_66227;
			}
			else {
				result_66419 = (dest_66227 === null || dest_66227 === undefined) ? {} : dest_66227;
			}
			}
			nimCopyAux(result_66419, src_66228, ti_66229.node);
			break;
		case 24:
		case 4:
		case 27:
		case 16:
			      if (src_66228 === null) {
        result_66419 = null;
      }
      else {
        if (dest_66227 === null || dest_66227 === undefined) {
          dest_66227 = new Array(src_66228.length);
        }
        else {
          dest_66227.length = src_66228.length;
        }
        result_66419 = dest_66227;
        for (var i = 0; i < src_66228.length; ++i) {
          result_66419[i] = nimCopy(result_66419[i], src_66228[i], ti_66229.base);
        }
      }
    
			break;
		case 28:
			      if (src_66228 !== null) {
        result_66419 = src_66228.slice(0);
      }
    
			break;
		default: 
			result_66419 = src_66228;
			break;
		}

	return result_66419;

}

function arrayConstr(len_66486, value_66487, typ_66488) {
		    var result = new Array(len_66486);
    for (var i = 0; i < len_66486; ++i) result[i] = nimCopy(null, value_66487, typ_66488);
    return result;
  

	
}

function cstrToNimstr(c_65275) {
		  var ln = c_65275.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_65275.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_65275.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

	
}

function toJSStr(s_65292) {
		  if (s_65292 === null) return "";
  var len = s_65292.length;
  var asciiPart = new Array(len);
  var fcc = String.fromCharCode;
  var nonAsciiPart = null;
  var nonAsciiOffset = 0;
  for (var i = 0; i < len; ++i) {
    if (nonAsciiPart !== null) {
      var offset = (i - nonAsciiOffset) * 2;
      var code = s_65292[i].toString(16);
      if (code.length == 1) {
        code = "0"+code;
      }
      nonAsciiPart[offset] = "%";
      nonAsciiPart[offset + 1] = code;
    }
    else if (s_65292[i] < 128)
      asciiPart[i] = fcc(s_65292[i]);
    else {
      asciiPart.length = i;
      nonAsciiOffset = i;
      nonAsciiPart = new Array((len - i) * 2);
      --i;
    }
  }
  asciiPart = asciiPart.join("");
  return (nonAsciiPart === null) ?
      asciiPart : asciiPart + decodeURIComponent(nonAsciiPart.join(""));
  

	
}

function raiseException(e_63618, ename_63619) {
		e_63618.name = ename_63619;
		if ((excHandler == 0)) {
		unhandledException(e_63618);
		}
		
		e_63618.trace = nimCopy(null, raw_write_stack_trace_63468(), NTI43040);
		throw e_63618;

	
}

function addInt(a_65603, b_65604) {
		    var result = a_65603 + b_65604;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}

function chckIndx(i_66505, a_66506, b_66507) {
			var Tmp1;

	var result_66508 = 0;

	BeforeRet: do {
			if (!(a_66506 <= i_66505)) Tmp1 = false; else {				Tmp1 = (i_66505 <= b_66507);			}		if (Tmp1) {
		result_66508 = i_66505;
		break BeforeRet;
		}
		else {
		raiseIndexError(i_66505, a_66506, b_66507);
		}
		
	} while (false);

	return result_66508;

}

function subInt(a_65621, b_65622) {
		    var result = a_65621 - b_65622;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}
var ConstSet2 = setConstr([65, 90]);

function chckRange(i_66524, a_66525, b_66526) {
			var Tmp1;

	var result_66527 = 0;

	BeforeRet: do {
			if (!(a_66525 <= i_66524)) Tmp1 = false; else {				Tmp1 = (i_66524 <= b_66526);			}		if (Tmp1) {
		result_66527 = i_66524;
		break BeforeRet;
		}
		else {
		raiseRangeError();
		}
		
	} while (false);

	return result_66527;

}
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_65639, b_65640) {
		    var result = a_65639 * b_65640;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);

function nimMax(a_65958, b_65959) {
		var Tmp1;

	var result_65960 = 0;

	BeforeRet: do {
		if ((b_65959 <= a_65958)) {
		Tmp1 = a_65958;
		}
		else {
		Tmp1 = b_65959;
		}
		
		result_65960 = Tmp1;
		break BeforeRet;
	} while (false);

	return result_65960;

}

function nimMin(a_65940, b_65941) {
		var Tmp1;

	var result_65942 = 0;

	BeforeRet: do {
		if ((a_65940 <= b_65941)) {
		Tmp1 = a_65940;
		}
		else {
		Tmp1 = b_65941;
		}
		
		result_65942 = Tmp1;
		break BeforeRet;
	} while (false);

	return result_65942;

}
var nim_program_result = 0;
var global_raise_hook_60618 = [null];
var local_raise_hook_60623 = [null];
var out_of_mem_hook_60626 = [null];
  if (!Math.trunc) {
    Math.trunc = function(v) {
      v = +v;
      if (!isFinite(v)) return v;

      return (v - v % 1)   ||   (v < 0 ? -0 : v === 0 ? v : 0);
    };
  }
var alternative_200315 = [null];

function is_fat_pointer_66201(ti_66203) {
	var result_66204 = false;

	BeforeRet: do {
		result_66204 = !((ConstSet1[ti_66203.base.kind] != undefined));
		break BeforeRet;
	} while (false);

	return result_66204;

}

function nimCopyAux(dest_66232, src_66233, n_66235) {
		switch (n_66235.kind) {
		case 0:
			break;
		case 1:
			      dest_66232[n_66235.offset] = nimCopy(dest_66232[n_66235.offset], src_66233[n_66235.offset], n_66235.typ);
    
			break;
		case 2:
			    for (var i = 0; i < n_66235.sons.length; i++) {
      nimCopyAux(dest_66232, src_66233, n_66235.sons[i]);
    }
    
			break;
		case 3:
			      dest_66232[n_66235.offset] = nimCopy(dest_66232[n_66235.offset], src_66233[n_66235.offset], n_66235.typ);
      for (var i = 0; i < n_66235.sons.length; ++i) {
        nimCopyAux(dest_66232, src_66233, n_66235.sons[i][1]);
      }
    
			break;
		}

	
}

function add_60638(x_60641, x_60641_Idx, y_60642) {
		      if (x_60641[x_60641_Idx] === null) { x_60641[x_60641_Idx] = []; }
      var off = x_60641[x_60641_Idx].length;
      x_60641[x_60641_Idx].length += y_60642.length;
      for (var i = 0; i < y_60642.length; ++i) {
        x_60641[x_60641_Idx][off+i] = y_60642.charCodeAt(i);
      }
    

	
}

function aux_write_stack_trace_63151(f_63153) {
					var Tmp3;

	var result_63154 = [null];

		var it_63162 = f_63153;
		var i_63164 = 0;
		var total_63166 = 0;
		var temp_frames_63173 = arrayConstr(64, {Field0: null, Field1: 0}, NTI63156);
		L1: do {
				L2: while (true) {
					if (!!((it_63162 == null))) Tmp3 = false; else {						Tmp3 = (i_63164 <= 63);					}				if (!Tmp3) break L2;
					temp_frames_63173[i_63164].Field0 = it_63162.procname;
					temp_frames_63173[i_63164].Field1 = it_63162.line;
					i_63164 += 1;
					total_63166 += 1;
					it_63162 = it_63162.prev;
				}
		} while(false);
		L4: do {
				L5: while (true) {
				if (!!((it_63162 == null))) break L5;
					total_63166 += 1;
					it_63162 = it_63162.prev;
				}
		} while(false);
		result_63154[0] = nimCopy(null, [], NTI43040);
		if (!((total_63166 == i_63164))) {
		if (result_63154[0] != null) { result_63154[0] = (result_63154[0]).concat(makeNimstrLit("(")); } else { result_63154[0] = makeNimstrLit("("); };
		if (result_63154[0] != null) { result_63154[0] = (result_63154[0]).concat(cstrToNimstr(((total_63166 - i_63164))+"")); } else { result_63154[0] = cstrToNimstr(((total_63166 - i_63164))+"").slice(); };
		if (result_63154[0] != null) { result_63154[0] = (result_63154[0]).concat(makeNimstrLit(" calls omitted) ...\x0A")); } else { result_63154[0] = makeNimstrLit(" calls omitted) ...\x0A"); };
		}
		
		L6: do {
			var j_63421 = 0;
			var colontmp__200456 = 0;
			colontmp__200456 = (i_63164 - 1);
			var res_200461 = colontmp__200456;
			L7: do {
					L8: while (true) {
					if (!(0 <= res_200461)) break L8;
						j_63421 = res_200461;
						add_60638(result_63154, 0, temp_frames_63173[j_63421].Field0);
						if ((0 < temp_frames_63173[j_63421].Field1)) {
						if (result_63154[0] != null) { result_63154[0] = (result_63154[0]).concat(makeNimstrLit(", line: ")); } else { result_63154[0] = makeNimstrLit(", line: "); };
						if (result_63154[0] != null) { result_63154[0] = (result_63154[0]).concat(cstrToNimstr((temp_frames_63173[j_63421].Field1)+"")); } else { result_63154[0] = cstrToNimstr((temp_frames_63173[j_63421].Field1)+"").slice(); };
						}
						
						if (result_63154[0] != null) { result_63154[0] = (result_63154[0]).concat(makeNimstrLit("\x0A")); } else { result_63154[0] = makeNimstrLit("\x0A"); };
						res_200461 -= 1;
					}
			} while(false);
		} while(false);

	return result_63154[0];

}

function raw_write_stack_trace_63468() {
	var result_63470 = null;

		if (!((framePtr == null))) {
		result_63470 = nimCopy(null, (makeNimstrLit("Traceback (most recent call last)\x0A") || []).concat(aux_write_stack_trace_63151(framePtr) || []), NTI43040);
		}
		else {
			result_63470 = nimCopy(null, makeNimstrLit("No stack traceback available\x0A"), NTI43040);
		}
		

	return result_63470;

}

function unhandledException(e_63529) {
		var buf_63530 = [[]];
		if (!(((e_63529.message != null ? e_63529.message.length : 0) == 0))) {
		if (buf_63530[0] != null) { buf_63530[0] = (buf_63530[0]).concat(makeNimstrLit("Error: unhandled exception: ")); } else { buf_63530[0] = makeNimstrLit("Error: unhandled exception: "); };
		if (buf_63530[0] != null) { buf_63530[0] = (buf_63530[0]).concat(e_63529.message); } else { buf_63530[0] = e_63529.message.slice(); };
		}
		else {
		if (buf_63530[0] != null) { buf_63530[0] = (buf_63530[0]).concat(makeNimstrLit("Error: unhandled exception")); } else { buf_63530[0] = makeNimstrLit("Error: unhandled exception"); };
		}
		
		if (buf_63530[0] != null) { buf_63530[0] = (buf_63530[0]).concat(makeNimstrLit(" [")); } else { buf_63530[0] = makeNimstrLit(" ["); };
		add_60638(buf_63530, 0, e_63529.name);
		if (buf_63530[0] != null) { buf_63530[0] = (buf_63530[0]).concat(makeNimstrLit("]\x0A")); } else { buf_63530[0] = makeNimstrLit("]\x0A"); };
		if (buf_63530[0] != null) { buf_63530[0] = (buf_63530[0]).concat(raw_write_stack_trace_63468()); } else { buf_63530[0] = raw_write_stack_trace_63468().slice(); };
		var cbuf_63601 = toJSStr(buf_63530[0]);
		framePtr = null;
		  if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_63601);
  }
  else {
    throw cbuf_63601;
  }
  

	
}

function raiseOverflow() {
		var e_64046 = null;
		e_64046 = {m_type: NTI46846, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		e_64046.message = nimCopy(null, makeNimstrLit("over- or underflow"), NTI43040);
		e_64046.parent = null;
		raiseException(e_64046, "OverflowError");

	
}

function is_whitespace_199654(text_199656) {
		     return !/[^\s]/.test(text_199656);
  

	
}

function is_whitespace_199671(x_199673) {
		var Tmp1;
		var Tmp2;

	var result_199674 = false;

	var F={procname:"dochack.isWhitespace",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 134;
		if (!(x_199673.nodeName == "#text")) Tmp2 = false; else {			Tmp2 = is_whitespace_199654(x_199673.textContent);		}		if (Tmp2) Tmp1 = true; else {			Tmp1 = (x_199673.nodeName == "#comment");		}		result_199674 = Tmp1;
	framePtr = F.prev;

	return result_199674;

}

function raiseIndexError(i_64643, a_64644, b_64645) {
		var e_64802 = null;
		e_64802 = {m_type: NTI46858, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		e_64802.message = nimCopy(null, (makeNimstrLit("index ") || []).concat(cstrToNimstr((i_64643)+"") || [],makeNimstrLit(" not in ") || [],cstrToNimstr((a_64644)+"") || [],makeNimstrLit(" .. ") || [],cstrToNimstr((b_64645)+"") || []), NTI43040);
		e_64802.parent = null;
		raiseException(e_64802, "IndexError");

	
}

function to_toc_199688(x_199690, father_199691) {
								var Tmp5;
						var Tmp6;
						var Tmp7;
						var Tmp8;
			var Tmp15;

	var F={procname:"dochack.toToc",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if ((x_199690.nodeName == "UL")) {
		F.line = 139;
		var f_199710 = {heading: null, kids: [], sortId: (father_199691.kids != null ? father_199691.kids.length : 0), doSort: false};
		F.line = 140;
		var i_199712 = 0;
		L1: do {
			F.line = 141;
				L2: while (true) {
				if (!(i_199712 < x_199690.childNodes.length)) break L2;
					F.line = 142;
					var nxt_199713 = addInt(i_199712, 1);
					L3: do {
						F.line = 143;
							L4: while (true) {
								if (!(nxt_199713 < x_199690.childNodes.length)) Tmp5 = false; else {									Tmp5 = is_whitespace_199671(x_199690.childNodes[nxt_199713]);								}							if (!Tmp5) break L4;
								F.line = 144;
								nxt_199713 = addInt(nxt_199713, 1);
							}
					} while(false);
						if (!(nxt_199713 < x_199690.childNodes.length)) Tmp8 = false; else {							Tmp8 = (x_199690.childNodes[i_199712].nodeName == "LI");						}						if (!Tmp8) Tmp7 = false; else {							Tmp7 = (x_199690.childNodes[i_199712].childNodes.length == 1);						}						if (!Tmp7) Tmp6 = false; else {							Tmp6 = (x_199690.childNodes[nxt_199713].nodeName == "UL");						}					if (Tmp6) {
					F.line = 147;
					var e_199738 = {heading: x_199690.childNodes[i_199712].childNodes[0], kids: [], sortId: (f_199710.kids != null ? f_199710.kids.length : 0), doSort: false};
					F.line = 148;
					var it_199739 = x_199690.childNodes[nxt_199713];
					L9: do {
						F.line = 149;
						var j_199747 = 0;
						F.line = 2638;
						var colontmp__200432 = 0;
						F.line = 149;
						colontmp__200432 = it_199739.childNodes.length;
						F.line = 2639;
						var i_200433 = 0;
						L10: do {
							F.line = 2640;
								L11: while (true) {
								if (!(i_200433 < colontmp__200432)) break L11;
									F.line = 149;
									j_199747 = i_200433;
									F.line = 150;
									to_toc_199688(it_199739.childNodes[j_199747], e_199738);
									F.line = 2642;
									i_200433 = addInt(i_200433, 1);
								}
						} while(false);
					} while(false);
					F.line = 151;
					if (f_199710.kids != null) { f_199710.kids.push(e_199738); } else { f_199710.kids = [e_199738]; };
					F.line = 152;
					i_199712 = addInt(nxt_199713, 1);
					}
					else {
						F.line = 154;
						to_toc_199688(x_199690.childNodes[i_199712], f_199710);
						F.line = 155;
						i_199712 = addInt(i_199712, 1);
					}
					
				}
		} while(false);
		F.line = 156;
		if (father_199691.kids != null) { father_199691.kids.push(f_199710); } else { father_199691.kids = [f_199710]; };
		}
		else {
		if (is_whitespace_199671(x_199690)) {
		}
		else {
		if ((x_199690.nodeName == "LI")) {
		F.line = 160;
		var idx_199782 = [];
		L12: do {
			F.line = 161;
			var i_199790 = 0;
			F.line = 2638;
			var colontmp__200437 = 0;
			F.line = 161;
			colontmp__200437 = x_199690.childNodes.length;
			F.line = 2639;
			var i_200438 = 0;
			L13: do {
				F.line = 2640;
					L14: while (true) {
					if (!(i_200438 < colontmp__200437)) break L14;
						F.line = 161;
						i_199790 = i_200438;
						if (!(is_whitespace_199671(x_199690.childNodes[i_199790]))) {
						F.line = 162;
						if (idx_199782 != null) { idx_199782.push(i_199790); } else { idx_199782 = [i_199790]; };
						}
						
						F.line = 2642;
						i_200438 = addInt(i_200438, 1);
					}
			} while(false);
		} while(false);
			if (!((idx_199782 != null ? idx_199782.length : 0) == 2)) Tmp15 = false; else {				Tmp15 = (x_199690.childNodes[idx_199782[chckIndx(1, 0, idx_199782.length+0-1)-0]].nodeName == "UL");			}		if (Tmp15) {
		F.line = 164;
		var e_199821 = {heading: x_199690.childNodes[idx_199782[chckIndx(0, 0, idx_199782.length+0-1)-0]], kids: [], sortId: (father_199691.kids != null ? father_199691.kids.length : 0), doSort: false};
		F.line = 166;
		var it_199822 = x_199690.childNodes[idx_199782[chckIndx(1, 0, idx_199782.length+0-1)-0]];
		L16: do {
			F.line = 167;
			var j_199830 = 0;
			F.line = 2638;
			var colontmp__200443 = 0;
			F.line = 167;
			colontmp__200443 = it_199822.childNodes.length;
			F.line = 2639;
			var i_200444 = 0;
			L17: do {
				F.line = 2640;
					L18: while (true) {
					if (!(i_200444 < colontmp__200443)) break L18;
						F.line = 167;
						j_199830 = i_200444;
						F.line = 168;
						to_toc_199688(it_199822.childNodes[j_199830], e_199821);
						F.line = 2642;
						i_200444 = addInt(i_200444, 1);
					}
			} while(false);
		} while(false);
		F.line = 169;
		if (father_199691.kids != null) { father_199691.kids.push(e_199821); } else { father_199691.kids = [e_199821]; };
		}
		else {
			L19: do {
				F.line = 171;
				var i_199845 = 0;
				F.line = 2638;
				var colontmp__200448 = 0;
				F.line = 171;
				colontmp__200448 = x_199690.childNodes.length;
				F.line = 2639;
				var i_200449 = 0;
				L20: do {
					F.line = 2640;
						L21: while (true) {
						if (!(i_200449 < colontmp__200448)) break L21;
							F.line = 171;
							i_199845 = i_200449;
							F.line = 172;
							to_toc_199688(x_199690.childNodes[i_199845], father_199691);
							F.line = 2642;
							i_200449 = addInt(i_200449, 1);
						}
				} while(false);
			} while(false);
		}
		
		}
		else {
			F.line = 174;
		if (father_199691.kids != null) { father_199691.kids.push({heading: x_199690, kids: [], sortId: (father_199691.kids != null ? father_199691.kids.length : 0), doSort: false}); } else { father_199691.kids = [{heading: x_199690, kids: [], sortId: (father_199691.kids != null ? father_199691.kids.length : 0), doSort: false}]; };
		}
		}}
	framePtr = F.prev;

	
}

function extract_items_199339(x_199341, heading_199342, items_199345, items_199345_Idx) {
			var Tmp1;

	var F={procname:"dochack.extractItems",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((x_199341 == null)) {
		F.line = 81;
		break BeforeRet;
		}
		
			if (!!((x_199341.heading == null))) Tmp1 = false; else {				Tmp1 = (x_199341.heading.textContent == heading_199342);			}		if (Tmp1) {
		L2: do {
			F.line = 83;
			var i_199374 = 0;
			F.line = 2638;
			var colontmp__200473 = 0;
			F.line = 83;
			colontmp__200473 = (x_199341.kids != null ? x_199341.kids.length : 0);
			F.line = 2639;
			var i_200474 = 0;
			L3: do {
				F.line = 2640;
					L4: while (true) {
					if (!(i_200474 < colontmp__200473)) break L4;
						F.line = 83;
						i_199374 = i_200474;
						F.line = 84;
						if (items_199345[items_199345_Idx] != null) { items_199345[items_199345_Idx].push(x_199341.kids[chckIndx(i_199374, 0, x_199341.kids.length+0-1)-0].heading); } else { items_199345[items_199345_Idx] = [x_199341.kids[chckIndx(i_199374, 0, x_199341.kids.length+0-1)-0].heading]; };
						F.line = 2642;
						i_200474 = addInt(i_200474, 1);
					}
			} while(false);
		} while(false);
		}
		else {
			L5: do {
				F.line = 86;
				var i_199394 = 0;
				F.line = 2638;
				var colontmp__200478 = 0;
				F.line = 86;
				colontmp__200478 = (x_199341.kids != null ? x_199341.kids.length : 0);
				F.line = 2639;
				var i_200479 = 0;
				L6: do {
					F.line = 2640;
						L7: while (true) {
						if (!(i_200479 < colontmp__200478)) break L7;
							F.line = 86;
							i_199394 = i_200479;
							F.line = 87;
							var it_199395 = x_199341.kids[chckIndx(i_199394, 0, x_199341.kids.length+0-1)-0];
							F.line = 88;
							extract_items_199339(it_199395, heading_199342, items_199345, items_199345_Idx);
							F.line = 2642;
							i_200479 = addInt(i_200479, 1);
						}
				} while(false);
			} while(false);
		}
		
	} while (false);
	framePtr = F.prev;

	
}

function tree_199020(tag_199022, kids_199024) {
	var result_199025 = null;

	var F={procname:"dochack.tree",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 11;
		result_199025 = document.createElement(toJSStr(tag_199022));
		L1: do {
			F.line = 12;
			var k_199056 = null;
			F.line = 3;
			var i_200496 = 0;
			L2: do {
				F.line = 4;
					L3: while (true) {
					if (!(i_200496 < (kids_199024 != null ? kids_199024.length : 0))) break L3;
						F.line = 12;
						k_199056 = kids_199024[chckIndx(i_200496, 0, kids_199024.length+0-1)-0];
						F.line = 13;
						result_199025.appendChild(k_199056);
						F.line = 6;
						i_200496 = addInt(i_200496, 1);
					}
			} while(false);
		} while(false);
	framePtr = F.prev;

	return result_199025;

}

function text_199152(s_199154) {
	var result_199155 = null;

	var F={procname:"dochack.text",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 27;
		result_199155 = document.createTextNode(s_199154);
	framePtr = F.prev;

	return result_199155;

}

function sys_fatal_56862(message_56866) {
	var F={procname:"sysFatal.sysFatal",prev:framePtr,filename:"../../lib/system/fatal.nim",line:0};
	framePtr = F;
		F.line = 34;
		var e_57007 = null;
		F.line = 37;
		e_57007 = {m_type: NTI46850, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		F.line = 38;
		e_57007.message = nimCopy(null, message_56866, NTI43040);
		F.line = 39;
		raiseException(e_57007, "AssertionError");
	framePtr = F.prev;

	
}

function raise_assert_56858(msg_56860) {
	var F={procname:"assertions.raiseAssert",prev:framePtr,filename:"../../lib/system/assertions.nim",line:0};
	framePtr = F;
		F.line = 20;
		sys_fatal_56862(msg_56860);
	framePtr = F.prev;

	
}

function failed_assert_impl_57055(msg_57057) {
	var F={procname:"assertions.failedAssertImpl",prev:framePtr,filename:"../../lib/system/assertions.nim",line:0};
	framePtr = F;
		F.line = 27;
		raise_assert_56858(msg_57057);
	framePtr = F.prev;

	
}

function uncovered_199940(x_199942) {
			var Tmp1;
		var Tmp2;

	var result_199943 = null;

	var F={procname:"dochack.uncovered",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
			if (!((x_199942.kids != null ? x_199942.kids.length : 0) == 0)) Tmp1 = false; else {				Tmp1 = !((x_199942.heading == null));			}		if (Tmp1) {
		F.line = 194;
		if (!(x_199942.heading.hasOwnProperty('__karaxMarker__'))) {
		Tmp2 = x_199942;
		}
		else {
		Tmp2 = null;
		}
		
		result_199943 = Tmp2;
		break BeforeRet;
		}
		
		F.line = 195;
		result_199943 = {heading: x_199942.heading, kids: [], sortId: x_199942.sortId, doSort: x_199942.doSort};
		L3: do {
			F.line = 197;
			var i_199982 = 0;
			F.line = 2638;
			var colontmp__200508 = 0;
			F.line = 197;
			colontmp__200508 = (x_199942.kids != null ? x_199942.kids.length : 0);
			F.line = 2639;
			var i_200509 = 0;
			L4: do {
				F.line = 2640;
					L5: while (true) {
					if (!(i_200509 < colontmp__200508)) break L5;
						F.line = 197;
						i_199982 = i_200509;
						F.line = 198;
						var y_199983 = uncovered_199940(x_199942.kids[chckIndx(i_199982, 0, x_199942.kids.length+0-1)-0]);
						if (!((y_199983 == null))) {
						F.line = 199;
						if (result_199943.kids != null) { result_199943.kids.push(y_199983); } else { result_199943.kids = [y_199983]; };
						}
						
						F.line = 2642;
						i_200509 = addInt(i_200509, 1);
					}
			} while(false);
		} while(false);
		if (((result_199943.kids != null ? result_199943.kids.length : 0) == 0)) {
		F.line = 200;
		result_199943 = null;
		}
		
	} while (false);
	framePtr = F.prev;

	return result_199943;

}

function merge_tocs_200017(orig_200019, news_200020) {
	var result_200021 = null;

	var F={procname:"dochack.mergeTocs",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 203;
		result_200021 = uncovered_199940(orig_200019);
		if ((result_200021 == null)) {
		F.line = 205;
		result_200021 = news_200020;
		}
		else {
			L1: do {
				F.line = 207;
				var i_200042 = 0;
				F.line = 2638;
				var colontmp__200502 = 0;
				F.line = 207;
				colontmp__200502 = (news_200020.kids != null ? news_200020.kids.length : 0);
				F.line = 2639;
				var i_200503 = 0;
				L2: do {
					F.line = 2640;
						L3: while (true) {
						if (!(i_200503 < colontmp__200502)) break L3;
							F.line = 207;
							i_200042 = i_200503;
							F.line = 208;
							if (result_200021.kids != null) { result_200021.kids.push(news_200020.kids[chckIndx(i_200042, 0, news_200020.kids.length+0-1)-0]); } else { result_200021.kids = [news_200020.kids[chckIndx(i_200042, 0, news_200020.kids.length+0-1)-0]]; };
							F.line = 2642;
							i_200503 = addInt(i_200503, 1);
						}
				} while(false);
			} while(false);
		}
		
	framePtr = F.prev;

	return result_200021;

}

function build_toc_200063(orig_200065, types_200067, procs_200068) {
	var result_200069 = null;

	var F={procname:"dochack.buildToc",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 211;
		var new_stuff_200083 = {heading: null, kids: [], doSort: true, sortId: 0};
		L1: do {
			F.line = 212;
			var t_200214 = null;
			F.line = 185;
			var i_200491 = 0;
			F.line = 186;
			var l_200492 = (types_200067 != null ? types_200067.length : 0);
			L2: do {
				F.line = 187;
					L3: while (true) {
					if (!(i_200491 < l_200492)) break L3;
						F.line = 212;
						t_200214 = types_200067[chckIndx(i_200491, 0, types_200067.length+0-1)-0];
						F.line = 213;
						var c_200228 = {heading: t_200214.cloneNode(true), kids: [], doSort: true, sortId: 0};
						F.line = 214;
						t_200214.__karaxMarker__ = true;
						L4: do {
							F.line = 215;
							var p_200235 = null;
							F.line = 185;
							var i_200488 = 0;
							F.line = 186;
							var l_200489 = (procs_200068 != null ? procs_200068.length : 0);
							L5: do {
								F.line = 187;
									L6: while (true) {
									if (!(i_200488 < l_200489)) break L6;
										F.line = 215;
										p_200235 = procs_200068[chckIndx(i_200488, 0, procs_200068.length+0-1)-0];
										if (!(p_200235.hasOwnProperty('__karaxMarker__'))) {
										F.line = 217;
										var xx_200236 = p_200235.parentNode.getElementsByClassName("attachedType");
										if ((((xx_200236 != null ? xx_200236.length : 0) == 1) && (xx_200236[chckIndx(0, 0, xx_200236.length+0-1)-0].textContent == t_200214.textContent))) {
										F.line = 220;
										var q_200244 = tree_199020(makeNimstrLit("A"), [text_199152(p_200235.title)]);
										F.line = 221;
										q_200244.setAttribute("href", p_200235.getAttribute("href"));
										F.line = 222;
										if (c_200228.kids != null) { c_200228.kids.push({heading: q_200244, kids: [], sortId: 0, doSort: false}); } else { c_200228.kids = [{heading: q_200244, kids: [], sortId: 0, doSort: false}]; };
										F.line = 223;
										p_200235.__karaxMarker__ = true;
										}
										
										}
										
										F.line = 189;
										i_200488 = addInt(i_200488, 1);
										if (!(((procs_200068 != null ? procs_200068.length : 0) == l_200489))) {
										F.line = 190;
										failed_assert_impl_57055(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system/iterators.nim(190, 11) `len(a) == L` the length of the seq changed while iterating over it"));
										}
										
									}
							} while(false);
						} while(false);
						F.line = 224;
						if (new_stuff_200083.kids != null) { new_stuff_200083.kids.push(c_200228); } else { new_stuff_200083.kids = [c_200228]; };
						F.line = 189;
						i_200491 = addInt(i_200491, 1);
						if (!(((types_200067 != null ? types_200067.length : 0) == l_200492))) {
						F.line = 190;
						failed_assert_impl_57055(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system/iterators.nim(190, 11) `len(a) == L` the length of the seq changed while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		F.line = 225;
		result_200069 = merge_tocs_200017(orig_200065, new_stuff_200083);
	framePtr = F.prev;

	return result_200069;

}

function add_199085(parent_199087, kid_199088) {
			var Tmp1;
				var Tmp2;

	var F={procname:"dochack.add",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
			if (!(parent_199087.nodeName == "TR")) Tmp1 = false; else {				if ((kid_199088.nodeName == "TD")) Tmp2 = true; else {					Tmp2 = (kid_199088.nodeName == "TH");				}				Tmp1 = Tmp2;			}		if (Tmp1) {
		F.line = 18;
		var k_199089 = document.createElement("TD");
		F.line = 19;
		k_199089.appendChild(kid_199088);
		F.line = 20;
		parent_199087.appendChild(k_199089);
		}
		else {
			F.line = 22;
		parent_199087.appendChild(kid_199088);
		}
		
	framePtr = F.prev;

	
}

function set_class_199103(e_199105, value_199106) {
	var F={procname:"dochack.setClass",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 25;
		e_199105.setAttribute("class", toJSStr(value_199106));
	framePtr = F.prev;

	
}

function to_html_199424(x_199426, is_root_199427) {
			var Tmp1;

		function HEX3Aanonymous_199467(a_199469, b_199470) {
					var Tmp1;

			var result_199471 = 0;

			var F={procname:"toHtml.:anonymous",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
			BeforeRet: do {
					if (!!((a_199469.heading == null))) Tmp1 = false; else {						Tmp1 = !((b_199470.heading == null));					}				if (Tmp1) {
				F.line = 106;
				var x_199488 = a_199469.heading.textContent;
				F.line = 107;
				var y_199489 = b_199470.heading.textContent;
				if ((x_199488 < y_199489)) {
				F.line = 108;
				result_199471 = -1;
				break BeforeRet;
				}
				
				if ((y_199489 < x_199488)) {
				F.line = 109;
				result_199471 = 1;
				break BeforeRet;
				}
				
				F.line = 110;
				result_199471 = 0;
				break BeforeRet;
				}
				else {
					F.line = 113;
					result_199471 = subInt(a_199469.sortId, b_199470.sortId);
					break BeforeRet;
				}
				
			} while (false);
			framePtr = F.prev;

			return result_199471;

		}

	var result_199428 = null;

	var F={procname:"dochack.toHtml",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((x_199426 == null)) {
		F.line = 91;
		result_199428 = null;
		break BeforeRet;
		}
		
		if (((x_199426.kids != null ? x_199426.kids.length : 0) == 0)) {
		if ((x_199426.heading == null)) {
		F.line = 93;
		result_199428 = null;
		break BeforeRet;
		}
		
		F.line = 94;
		result_199428 = x_199426.heading.cloneNode(true);
		break BeforeRet;
		}
		
		F.line = 95;
		result_199428 = tree_199020(makeNimstrLit("DIV"), []);
			if (!!((x_199426.heading == null))) Tmp1 = false; else {				Tmp1 = !(x_199426.heading.hasOwnProperty('__karaxMarker__'));			}		if (Tmp1) {
		F.line = 97;
		add_199085(result_199428, x_199426.heading.cloneNode(true));
		}
		
		F.line = 98;
		var ul_199464 = tree_199020(makeNimstrLit("UL"), []);
		if (is_root_199427) {
		F.line = 100;
		set_class_199103(ul_199464, makeNimstrLit("simple simple-toc"));
		}
		else {
			F.line = 102;
		set_class_199103(ul_199464, makeNimstrLit("simple"));
		}
		
		if (x_199426.doSort) {
		F.line = 104;
		x_199426.kids.sort(HEX3Aanonymous_199467);
		}
		
		L2: do {
			F.line = 115;
			var k_199614 = null;
			F.line = 183;
			var colontmp__200515 = null;
			F.line = 115;
			colontmp__200515 = x_199426.kids;
			F.line = 185;
			var i_200517 = 0;
			F.line = 186;
			var l_200518 = (colontmp__200515 != null ? colontmp__200515.length : 0);
			L3: do {
				F.line = 187;
					L4: while (true) {
					if (!(i_200517 < l_200518)) break L4;
						F.line = 115;
						k_199614 = colontmp__200515[chckIndx(i_200517, 0, colontmp__200515.length+0-1)-0];
						F.line = 116;
						var y_199615 = to_html_199424(k_199614, false);
						if (!((y_199615 == null))) {
						F.line = 118;
						add_199085(ul_199464, tree_199020(makeNimstrLit("LI"), [y_199615]));
						}
						
						F.line = 189;
						i_200517 = addInt(i_200517, 1);
						if (!(((colontmp__200515 != null ? colontmp__200515.length : 0) == l_200518))) {
						F.line = 190;
						failed_assert_impl_57055(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system/iterators.nim(190, 11) `len(a) == L` the length of the seq changed while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		if (!((ul_199464.childNodes.length == 0))) {
		F.line = 119;
		add_199085(result_199428, ul_199464);
		}
		
		if ((result_199428.childNodes.length == 0)) {
		F.line = 120;
		result_199428 = null;
		}
		
	} while (false);
	framePtr = F.prev;

	return result_199428;

}

function replace_by_id_199172(id_199174, new_tree_199175) {
	var F={procname:"dochack.replaceById",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 32;
		var x_199176 = document.getElementById(id_199174);
		F.line = 33;
		x_199176.parentNode.replaceChild(new_tree_199175, x_199176);
		F.line = 34;
		new_tree_199175.id = id_199174;
	framePtr = F.prev;

	
}

function togglevis_200329(d_200331) {
	var F={procname:"dochack.togglevis",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 230;
		    if (d_200331.style.display == 'none')
      d_200331.style.display = 'inline';
    else
      d_200331.style.display = 'none';
  
	framePtr = F.prev;

	
}

function groupBy(value_200347) {
	var F={procname:"dochack.groupBy",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 238;
		var toc_200348 = document.getElementById("toc-list");
		if ((alternative_200315[0] == null)) {
		F.line = 240;
		var tt_200367 = {heading: null, kids: [], sortId: 0, doSort: false};
		F.line = 241;
		to_toc_199688(toc_200348, tt_200367);
		F.line = 242;
		tt_200367 = tt_200367.kids[chckIndx(0, 0, tt_200367.kids.length+0-1)-0];
		F.line = 244;
		var types_200382 = [[]];
		F.line = 245;
		var procs_200397 = [[]];
		F.line = 247;
		extract_items_199339(tt_200367, "Types", types_200382, 0);
		F.line = 248;
		extract_items_199339(tt_200367, "Procs", procs_200397, 0);
		F.line = 249;
		extract_items_199339(tt_200367, "Converters", procs_200397, 0);
		F.line = 250;
		extract_items_199339(tt_200367, "Methods", procs_200397, 0);
		F.line = 251;
		extract_items_199339(tt_200367, "Templates", procs_200397, 0);
		F.line = 252;
		extract_items_199339(tt_200367, "Macros", procs_200397, 0);
		F.line = 253;
		extract_items_199339(tt_200367, "Iterators", procs_200397, 0);
		F.line = 255;
		var ntoc_200405 = build_toc_200063(tt_200367, types_200382[0], procs_200397[0]);
		F.line = 256;
		var x_200406 = to_html_199424(ntoc_200405, true);
		F.line = 257;
		alternative_200315[0] = tree_199020(makeNimstrLit("DIV"), [x_200406]);
		}
		
		if ((value_200347 == "type")) {
		F.line = 259;
		replace_by_id_199172("tocRoot", alternative_200315[0]);
		}
		else {
			F.line = 261;
		replace_by_id_199172("tocRoot", tree_199020(makeNimstrLit("DIV"), []));
		}
		
		F.line = 262;
		togglevis_200329(document.getElementById("toc-list"));
	framePtr = F.prev;

	
}
var db_200521 = [null];
var contents_200523 = [null];
var oldtoc_200959 = [null];
var timer_200960 = [null];

function raiseRangeError() {
		var e_64445 = null;
		e_64445 = {m_type: NTI46862, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		e_64445.message = nimCopy(null, makeNimstrLit("value out of range"), NTI43040);
		e_64445.parent = null;
		raiseException(e_64445, "RangeError");

	
}

function nsuToLowerAsciiChar(c_187980) {
	var result_187981 = 0;

	var F={procname:"strutils.toLowerAscii",prev:framePtr,filename:"../../lib/pure/strutils.nim",line:0};
	framePtr = F;
		if ((ConstSet2[c_187980] != undefined)) {
		F.line = 222;
		result_187981 = chckRange(addInt(c_187980, 32), 0, 255);
		}
		else {
			F.line = 224;
			result_187981 = c_187980;
		}
		
	framePtr = F.prev;

	return result_187981;

}

function fuzzy_match_198070(pattern_198072, str_198073) {
							var Tmp4;
							var Tmp5;
								var Tmp6;

	var result_198077 = {Field0: 0, Field1: false};

	var F={procname:"fuzzysearch.fuzzyMatch",prev:framePtr,filename:"fuzzysearch.nim",line:0};
	framePtr = F;
		F.line = 37;
		var score_state_198078 = -100;
		F.line = 38;
		var header_matched_198079 = false;
		F.line = 39;
		var unmatched_leading_char_count_198081 = 0;
		F.line = 40;
		var consecutive_match_count_198083 = 0;
		F.line = 41;
		var str_index_198085 = 0;
		F.line = 42;
		var pat_index_198087 = 0;
		F.line = 43;
		var score_198089 = 0;
		L1: do {
			F.line = 49;
				L2: while (true) {
				if (!((str_index_198085 < (str_198073 != null ? str_198073.length : 0)) && (pat_index_198087 < (pattern_198072 != null ? pattern_198072.length : 0)))) break L2;
					L3: do {
						F.line = 51;
						var pattern_char_198096 = nsuToLowerAsciiChar(pattern_198072.charCodeAt(chckIndx(pat_index_198087, 0, pattern_198072.length+0-1)-0));
						F.line = 52;
						var str_char_198097 = nsuToLowerAsciiChar(str_198073.charCodeAt(chckIndx(str_index_198085, 0, str_198073.length+0-1)-0));
						if ((ConstSet3[pattern_char_198096] != undefined)) {
						F.line = 56;
						pat_index_198087 = addInt(pat_index_198087, 1);
						F.line = 57;
						break L3;
						}
						
						if ((ConstSet4[str_char_198097] != undefined)) {
						F.line = 59;
						str_index_198085 = addInt(str_index_198085, 1);
						F.line = 60;
						break L3;
						}
						
						if ((!(header_matched_198079) && (str_char_198097 == 58))) {
						F.line = 65;
						header_matched_198079 = true;
						F.line = 66;
						score_state_198078 = -100;
						F.line = 67;
						score_198089 = Math.trunc(Math.floor((5.0000000000000000e-01 * score_198089)));
						F.line = 68;
						pat_index_198087 = 0;
						F.line = 69;
						str_index_198085 = addInt(str_index_198085, 1);
						F.line = 70;
						break L3;
						}
						
						if ((str_char_198097 == pattern_char_198096)) {
						F.line = 73;
						switch (score_state_198078) {
						case -100:
						case 20:
							F.line = 75;
							score_state_198078 = 10;
							break;
						case 0:
							F.line = 78;
							score_state_198078 = 5;
							F.line = 78;
							score_198089 = addInt(score_198089, score_state_198078);
							break;
						case 10:
						case 5:
							F.line = 81;
							consecutive_match_count_198083 = addInt(consecutive_match_count_198083, 1);
							F.line = 82;
							score_state_198078 = 5;
							F.line = 83;
							score_198089 = addInt(score_198089, mulInt(5, consecutive_match_count_198083));
							if ((score_state_198078 == 10)) {
							F.line = 86;
							score_198089 = addInt(score_198089, 10);
							}
							
							F.line = 88;
							var on_boundary_198172 = (pat_index_198087 == (pattern_198072 != null ? (pattern_198072.length-1) : -1));
							if ((!(on_boundary_198172) && (str_index_198085 < (str_198073 != null ? (str_198073.length-1) : -1)))) {
							F.line = 91;
							var next_pattern_char_198173 = nsuToLowerAsciiChar(pattern_198072.charCodeAt(chckIndx(addInt(pat_index_198087, 1), 0, pattern_198072.length+0-1)-0));
							F.line = 92;
							var next_str_char_198174 = nsuToLowerAsciiChar(str_198073.charCodeAt(chckIndx(addInt(str_index_198085, 1), 0, str_198073.length+0-1)-0));
							F.line = 95;
							if (!!((ConstSet5[next_str_char_198174] != undefined))) Tmp4 = false; else {								Tmp4 = !((next_str_char_198174 == next_pattern_char_198173));							}							on_boundary_198172 = Tmp4;
							}
							
							if (on_boundary_198172) {
							F.line = 100;
							score_state_198078 = 20;
							F.line = 100;
							score_198089 = addInt(score_198089, score_state_198078);
							}
							
							break;
						case -1:
						case -3:
							F.line = 103;
							if (!((ConstSet6[str_198073.charCodeAt(chckIndx(subInt(str_index_198085, 1), 0, str_198073.length+0-1)-0)] != undefined))) Tmp5 = true; else {								if (!(ConstSet7[str_198073.charCodeAt(chckIndx(subInt(str_index_198085, 1), 0, str_198073.length+0-1)-0)] != undefined)) Tmp6 = false; else {									Tmp6 = (ConstSet8[str_198073.charCodeAt(chckIndx(str_index_198085, 0, str_198073.length+0-1)-0)] != undefined);								}								Tmp5 = Tmp6;							}							var is_leading_char_198212 = Tmp5;
							if (is_leading_char_198212) {
							F.line = 110;
							score_state_198078 = 10;
							}
							else {
								F.line = 114;
								score_state_198078 = 0;
								F.line = 114;
								score_198089 = addInt(score_198089, score_state_198078);
							}
							
							break;
						}
						F.line = 115;
						pat_index_198087 = addInt(pat_index_198087, 1);
						}
						else {
							F.line = 118;
							switch (score_state_198078) {
							case -100:
								F.line = 120;
								score_state_198078 = -3;
								F.line = 120;
								score_198089 = addInt(score_198089, score_state_198078);
								break;
							case 5:
								F.line = 123;
								score_state_198078 = -1;
								F.line = 123;
								score_198089 = addInt(score_198089, score_state_198078);
								F.line = 124;
								consecutive_match_count_198083 = 0;
								break;
							case -3:
								if ((unmatched_leading_char_count_198081 < 3)) {
								F.line = 128;
								score_state_198078 = -3;
								F.line = 128;
								score_198089 = addInt(score_198089, score_state_198078);
								}
								
								F.line = 129;
								unmatched_leading_char_count_198081 = addInt(unmatched_leading_char_count_198081, 1);
								break;
							default: 
								F.line = 132;
								score_state_198078 = -1;
								F.line = 132;
								score_198089 = addInt(score_198089, score_state_198078);
								break;
							}
						}
						
						F.line = 134;
						str_index_198085 = addInt(str_index_198085, 1);
					} while(false);
				}
		} while(false);
		F.line = 137;
		var colontmp__201063 = nimMax(0, score_198089);
		F.line = 138;
		var colontmp__201064 = (0 < score_198089);
		F.line = 136;
		nimCopy(result_198077, {Field0: colontmp__201063, Field1: colontmp__201064}, NTI198074);
	framePtr = F.prev;

	return result_198077;

}

function text_199120(s_199122) {
	var result_199123 = null;

	var F={procname:"dochack.text",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 26;
		result_199123 = document.createTextNode(toJSStr(s_199122));
	framePtr = F.prev;

	return result_199123;

}

function dosearch_200555(value_200557) {

		function HEX3Aanonymous_200871(a_200880, b_200881) {
			var result_200885 = 0;

			var F={procname:"dosearch.:anonymous",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
				F.line = 305;
				result_200885 = subInt(b_200881["Field1"], a_200880["Field1"]);
			framePtr = F.prev;

			return result_200885;

		}

	var result_200558 = null;

	var F={procname:"dochack.dosearch",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if (((db_200521[0] != null ? db_200521[0].length : 0) == 0)) {
		F.line = 272;
		var stuff_200564 = null;
		F.line = 273;
		    var request = new XMLHttpRequest();
    request.open("GET", "theindex.html", false);
    request.send(null);

    var doc = document.implementation.createHTMLDocument("theindex");
    doc.documentElement.innerHTML = request.responseText;

    //parser=new DOMParser();
    //doc=parser.parseFromString("<html></html>", "text/html");

    stuff_200564 = doc.documentElement;
    
		F.line = 286;
		db_200521[0] = nimCopy(null, stuff_200564.getElementsByClassName("reference"), NTI86305);
		F.line = 287;
		contents_200523[0] = nimCopy(null, [], NTI200577);
		L1: do {
			F.line = 288;
			var ahref_200814 = null;
			F.line = 185;
			var i_201043 = 0;
			F.line = 186;
			var l_201044 = (db_200521[0] != null ? db_200521[0].length : 0);
			L2: do {
				F.line = 187;
					L3: while (true) {
					if (!(i_201043 < l_201044)) break L3;
						F.line = 288;
						ahref_200814 = db_200521[0][chckIndx(i_201043, 0, db_200521[0].length+0-1)-0];
						F.line = 289;
						if (contents_200523[0] != null) { contents_200523[0].push(ahref_200814.getAttribute("data-doc-search-tag")); } else { contents_200523[0] = [ahref_200814.getAttribute("data-doc-search-tag")]; };
						F.line = 189;
						i_201043 = addInt(i_201043, 1);
						if (!(((db_200521[0] != null ? db_200521[0].length : 0) == l_201044))) {
						F.line = 190;
						failed_assert_impl_57055(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system/iterators.nim(190, 11) `len(a) == L` the length of the seq changed while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		}
		
		F.line = 290;
		var ul_200825 = tree_199020(makeNimstrLit("UL"), []);
		F.line = 291;
		result_200558 = tree_199020(makeNimstrLit("DIV"), []);
		F.line = 292;
		set_class_199103(result_200558, makeNimstrLit("search_results"));
		F.line = 293;
		var matches_200844 = [];
		L4: do {
			F.line = 294;
			var i_200857 = 0;
			F.line = 2638;
			var colontmp__201050 = 0;
			F.line = 294;
			colontmp__201050 = (db_200521[0] != null ? db_200521[0].length : 0);
			F.line = 2639;
			var i_201051 = 0;
			L5: do {
				F.line = 2640;
					L6: while (true) {
					if (!(i_201051 < colontmp__201050)) break L6;
						F.line = 294;
						i_200857 = i_201051;
						L7: do {
							F.line = 295;
							var c_200858 = contents_200523[0][chckIndx(i_200857, 0, contents_200523[0].length+0-1)-0];
							if (((c_200858 == "Examples") || (c_200858 == "PEG construction"))) {
							F.line = 300;
							break L7;
							}
							
							F.line = 301;
							var colontmp__201060 = {Field0: 0, Field1: false};
							F.line = 301;
							var score_200859 = 0;
							F.line = 301;
							var matched_200860 = false;
							F.line = 301;
							nimCopy(colontmp__201060, fuzzy_match_198070(value_200557, c_200858), NTI198074);
							F.line = 301;
							score_200859 = colontmp__201060["Field0"];
							F.line = 301;
							matched_200860 = colontmp__201060["Field1"];
							if (matched_200860) {
							F.line = 303;
							if (matches_200844 != null) { matches_200844.push({Field0: db_200521[0][chckIndx(i_200857, 0, db_200521[0].length+0-1)-0], Field1: score_200859}); } else { matches_200844 = [{Field0: db_200521[0][chckIndx(i_200857, 0, db_200521[0].length+0-1)-0], Field1: score_200859}]; };
							}
							
						} while(false);
						F.line = 2642;
						i_201051 = addInt(i_201051, 1);
					}
			} while(false);
		} while(false);
		F.line = 305;
		matches_200844.sort(HEX3Aanonymous_200871);
		L8: do {
			F.line = 306;
			var i_200924 = 0;
			F.line = 2638;
			var colontmp__201056 = 0;
			F.line = 306;
			colontmp__201056 = nimMin((matches_200844 != null ? matches_200844.length : 0), 19);
			F.line = 2639;
			var i_201057 = 0;
			L9: do {
				F.line = 2640;
					L10: while (true) {
					if (!(i_201057 < colontmp__201056)) break L10;
						F.line = 306;
						i_200924 = i_201057;
						F.line = 307;
						matches_200844[chckIndx(i_200924, 0, matches_200844.length+0-1)-0]["Field0"].innerHTML = matches_200844[chckIndx(i_200924, 0, matches_200844.length+0-1)-0]["Field0"].getAttribute("data-doc-search-tag");
						F.line = 308;
						add_199085(ul_200825, tree_199020(makeNimstrLit("LI"), [matches_200844[chckIndx(i_200924, 0, matches_200844.length+0-1)-0]["Field0"]]));
						F.line = 2642;
						i_201057 = addInt(i_201057, 1);
					}
			} while(false);
		} while(false);
		if ((ul_200825.childNodes.length == 0)) {
		F.line = 310;
		add_199085(result_200558, tree_199020(makeNimstrLit("B"), [text_199120(makeNimstrLit("no search results"))]));
		}
		else {
			F.line = 312;
			add_199085(result_200558, tree_199020(makeNimstrLit("B"), [text_199120(makeNimstrLit("search results"))]));
			F.line = 313;
			add_199085(result_200558, ul_200825);
		}
		
	framePtr = F.prev;

	return result_200558;

}

function search() {

		function wrapper_200991() {
			var F={procname:"search.wrapper",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
				F.line = 320;
				var elem_200993 = document.getElementById("searchInput");
				F.line = 321;
				var value_200994 = elem_200993.value;
				if (!(((value_200994 != null ? value_200994.length : 0) == 0))) {
				if ((oldtoc_200959[0] == null)) {
				F.line = 324;
				oldtoc_200959[0] = document.getElementById("tocRoot");
				}
				
				F.line = 325;
				var results_201000 = dosearch_200555(value_200994);
				F.line = 326;
				replace_by_id_199172("tocRoot", results_201000);
				}
				else {
				if (!((oldtoc_200959[0] == null))) {
				F.line = 328;
				replace_by_id_199172("tocRoot", oldtoc_200959[0]);
				}
				}
			framePtr = F.prev;

			
		}

	var F={procname:"dochack.search",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if (!((timer_200960[0] == null))) {
		F.line = 330;
		clearTimeout(timer_200960[0]);
		}
		
		F.line = 331;
		timer_200960[0] = setTimeout(wrapper_200991, 400);
	framePtr = F.prev;

	
}
